### ISSUE TITLE
GOTO vs GOSUB (noob question)

### ISSUE THREAD

**Issue by frenchfaso** [neilsf/XC-BASIC#121]
Hello there,
what is the main difference between GOTO and GOSUB?
is GOTO faster because there is no return to calling point?
(but supposedly another GOTO to the continuation point..)
Thanks and sorry for the noobnes!

PS: is it ok to post questions here?

**Comment by neilsf** [comment]
Sure, you can ask questions here. They're both super simple: GOTO
translates to JMP and GOSUB translates to JSR. GOTO is indeed a little
faster because JSR first pushes the return address onto the stack and then
jumps to the destination. The difference is only 3 CPU cycles.

frenchfaso <notifications@github.com> ezt írta (időpont: 2020. aug. 28., P
18:10):

**Comment by frenchfaso** [comment]
that makes sense, thanks!
