### ISSUE TITLE
Number Formatting

### ISSUE THREAD

**Issue by Pontiac76** [neilsf/XC-BASIC#133]
I just found out about XCBasic this afternoon, and right after work, I started some basic (no pun) investigation to speed differences.  I plan on writing a simple program that I wrote in college for the PC/DOS, and the text animation I plan on having is probably going to be best suited for XCBasic instead of my writing ASM for the UI. :)

I wrote the following program:

```
10 print "{CLR}";
20 x=0
30 x=x+1
40 print "{HOME}";
50 print x
60 goto 30

```
I pasted this code into VICE (x64sc.exe) with appropriate fixes for {CLR} and {HOME}, and then compiled it into a PRG using xcbasic.

What I noticed is that the typed in variant running in C64 BASIC, there's a space before the number to indicate the sign of the number.  Positive in this case.  In the image on the right, the compiled code, there is no space.  Is this something intentional?

![image](https://user-images.githubusercontent.com/4532020/106075575-e0c45680-60db-11eb-8420-630eb8467989.png)

**Comment by neilsf** [comment]
Hi
Thanks for trying XC=BASIC!
Yes, it's intentional. CBM BASIC starts the number with space (positive) or - (negative) while XC=BASIC puts no space if it's positive.
However when you print floating point numbers in XC=BASIC, they'll be printed just like in CBM BASIC.
Although you should try to avoid using floating point, it's very slow compared to integers.

**Comment by Pontiac76** [comment]
Alright, thanks.
