### ISSUE TITLE
Implementation of binary code

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#19]
Not really an issue, but nontheless important: Is it possible to include binary code? Or is it planned? I especially think of including SIDs, fonts or images. 

I guess implementing sprites is possible through data arrays? Could work with char modification, too.

**Comment by neilsf** [comment]
Yes, it is planned, but not yet clear how exactly. One idea is to extend the DATA statement, for example:

`data sprites[] = _include("/path/to/binary/file")`

Where `_include` is a compiler directive that is expanded to raw values in compile-time. The values could then be accessed using normal array access.

Another important feature that has to be implemented at the same time is the address-of operator, because often you need direct access to binary data or other variables/arrays, e.g:

`let address = @sprites`

Then you can access the data using PEEK:

`let x = peek(address)`

.. which would be the same as

`let x = sprites[0]`

I think I'll schedule the above BEFORE the next major release, somewhere between versions 1.0 and 2.0.

Do you have any alternative idea? Any thoughts are welcome.

Ps. Yes, DATA can be useful to store sprite data. The only problem is that you have to copy the sprites to their final location because DATA will not assure where exactly the data is compiled. This is not very memory-efficient as you end up storing the sprites twice. To overcome this, I'm really thinking about giving the programmer the option to tell where the variables will go, for example:

`data somedata[] = 1, 2, 3 at $C000`

or even if you want to put a variable to the zero page:

`dim myfastvariable at $fe`

which can be a little dangerous but we, retro coders are not of the fastidious type, are we? :-D

**Comment by neilsf** [comment]
Actually, you can include binary data, but it's a little bit of tweaking. By using the binary (not the xcb.bat script) you can compile the BASIC source to DASM source. Then you can put an INCBIN statement into the assembly source and compile with DASM. Not very straightforward, but it should work.

**Comment by oliverhermanni** [comment]
Ha, I thought about that, too. ;) 

Well, I'll port my code first to learn more about XC-BASIC. Although I have starred this project some months ago I just started yesterday to use it. Sprites are not yet needed for the original code (char modification is, but I think I can handle this with POKE, there are not many chars I modified for Maze of Death. 

I'll be back later. ;)
