### ISSUE TITLE
Logical operators in POKE

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#22]
POKE and PEEK need support for AND + OR

Eg. for this example from the Programmer's Reference Guide

```
5 PRINT CHR$(142) : REM SWITCH TO UPPERCASE
10 POKE52, 48 : POKE56, 48 : CLR : REM RESERVE MEMORY FOR CHARACTERS
20 POKE56334, PEEK ( 56334 ) AND 254 : REM TURN OFF KEYSCAN INTERRUPT TIMER
30 POKE 1, PEEK(1) AND 251 : REM SWITCH IN CHARACTER
40 FORI = 0 TO 511 : POKEI + 12288 , PEEK ( I +53248 ) : NEXT
50 POKE 1, PEEK (1) OR 4 : REM SWITCH IN I/O
60 POKE56334, PEEK(56334) OR 1 : REM RESTART KEYSCAN INTERRUPT TIMER
70 END
```

**Comment by neilsf** [comment]
I've scheduled this to version 1.1 - thanks for raising attention.

For the time being, you can safely assume that the value held in memory location 1 is exactly 54 (binary 00110110), because that's what the XC-BASIC standard library sets up when starting your program. So you can do the binary calculations yourself and POKE constant values to location 1.

Please note that POKE-ing to locations 52 and 56 will not have any effect because you're not in the BASIC environment while running your program. You have to make sure that you put the character set in memory higher than your program (12288 is OK if the program is less than 10 kilobytes).

I will also add an important feature: to display the exact memory locations of your program after it's fully compiled.

**Comment by oliverhermanni** [comment]
Oh, of course. Silly me. ;)

**Comment by oliverhermanni** [comment]
Additional info: ANDing or ORing two values (or a var and a value) needs to be added also. 

Like in
```
t = i AND 3

**Comment by neilsf** [comment]
Fyi: three new operators will be added in version 1.1: AND, OR and XOR. They will work in any expression.

**Comment by neilsf** [comment]
It's out in version 1.1! Note that you have to use c-style operators: & | ^ to avoid confusion with conditional operators.
Example
`POKE 1, PEEK(1) & 251`
`POKE 1, PEEK(1) | 4`
