### ISSUE TITLE
The word end is not allowed as part of a variable.

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#24]
I wrote two variables, one called startpoint, the other endpoint. My source code doesn't compile then. I know, that end is a keyword, but other keywords seem to work fine.

**Comment by neilsf** [comment]
Thanks.

This is due to poor documentation. Identifiers may not start with a reserved keyword, the grammar definition won't allow this.

If we allowed keywords in the identifier, it would make serious confusion, for example:

```
letter = 6
let ter = 6
```
I'll update the docs.

Can you please write an example where it worked with a keyword? Because THAT is a bug if it did.

**Comment by oliverhermanni** [comment]
Yes, that's understandable.

I'm not sure right now, as I'm at work. I'll check later, when I'm back home.

**Comment by oliverhermanni** [comment]
Did you change the behaviour? Variables like end_point compile fine now, but the compiled program really ends then.

I can start variable names with CALL, CHARAT, CONST, END, FOR, NEXT, RETURN, ELSE, LET, REM

Fun fact: If I compile
```
call_point = 50
print call_point
```

the result is 50 in the running program.

`rem_point = 50` for itself compiles fine, but if I write

```
rem_point = 50
print rem_point
```

it does not compile.

**Comment by neilsf** [comment]
No change in version 1.0 since.

I can see now that the bug here is that it does not always give a compile error when you start a variable name with a keyword, although it should.

Many thanks for reporting. I'll release a hotfix before 1.1.

P.S `rem_point=50` compiles as a single REM statement :-)

**Comment by oliverhermanni** [comment]
I thought so. ;)

**Comment by neilsf** [comment]
Hotfix merged into master.
