### ISSUE TITLE
Suggestion: multiline IF ... ENDIF and IF ... ELSE ... ENDIF

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#27]
Multiline IF ... END and IF ... ELSE ... ENDIF would be nice. 

Sample:

I wanted to convert following line from BASIC V2 to XC-BASIC
```
120 b=a+a(j):if peek(b)=160 then poke b,j:poke a+a(j)/2,32:a=b:s=s+1:goto 110 
```
I can simulate IF ... ENDIF by using
```
loop1:
   [...]
if peek(b) <> 160 then goto loop2
poke b,j
r=aa[j]/2
poke a+r,32
a=b
s=s+1
goto loop1
loop2:
   print "x"
```
or - as I did in my labyrinth code (but will cleanup tonight):
```
loop1:
   [...]
if peek(b) = 160 then goto loop2
print "x"
[...]
loop2:
    poke b,j
    r=aa[j]/2
    poke a+r,32
    a=b
    s=s+1
    goto loop1
```
In this example I need to put my if-code behind the end of the code.

This would be much easier to write
```
if peek(b) = 160 then
    poke b,j
    r=aa[j]/2
    poke a+r,32
    a=b
    s=s+1
endif
```

**Comment by neilsf** [comment]
Thanks for the idea, I've been also thinking about adding support for statement blocks, like in Pascal, for example. However, it's not straightforward to implement, because it will immediately involve nested IF ... ENDIF blocks, e.g:

    if condition then
        if condition then
            [...]
        endif
    endif

and because BASIC, not being a structured language (it supports the nasty `GOTO` statement), one can easyly screw up the stack and make the program break.

The other, more BASIC-ish approach would be to allow multiple statements in one line separated by a colon `:`, just like in CBM BASIC.

I'll think about both. But now I'm spending all my free time on implementing floating-point support which is a major rewrite of many parts of the code.

**Comment by neilsf** [comment]
... actually, the same goes for `FOR ... NEXT`, you can screw it up with some badly designed `GOTO`s, so why not implementing `IF ... THEN` the same way?

**Comment by neilsf** [comment]
A new feature will come soon in the current develop branch (yet to be tested), the statement separator character (`:`). This, in combination with the line concatenation character (`~`) can be used to accomplish what you described above.

For example:

    a = 2 : b = 3
    if a < b then ~
      print "a is less than b" : ~
      print "as many statements here" : ~
      print "as you want"
    else ~
      <more statements>

Because of the `~` the entire `IF ... ELSE` above is treated as one line. Note that the `:` is important between the statements within.

I know it's not very beautiful, but works without introducing the ENDIF command.

**Comment by oliverhermanni** [comment]
Nice! Does that mean, one can put multiple commands in one line also by seperating them with : ?

**Comment by neilsf** [comment]
Yeah, just like in CBM BASIC ;-)
