### ISSUE TITLE
PROC...ENDPROC type mismatch on parameters (dev)

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#50]
Following code does return `ERROR: Argument type mismatch in file main.bas in line 14`. It does work, when I do `call anothertestfunction(1000,2000)`.

It must have to do with parameter types. Using `a!`, etc. works. 

I'm really not sure, where the problem is. The first PROC ... ENDPROC example in the wiki works fine, but basically I see no difference between the called proc arguments. The wiki example doesn't care about byte and integer.

```
proc testfunction (a, b)
   print "hello from testfunction with value",a
   print "and",b
endproc

proc anothertestfunction (c,d)
  call testfunction (c,d)
  print "and a hello from this function also!"
endproc

call anothertestfunction(1,2)

**Comment by neilsf** [comment]
Thanks for reporting. This was indeed a bug. Fixed now.

The problem was that the numbers 1 and 2 are considered to be bytes because they're between 0 and 255. This is fine, however CALL should implicitly convert them to the appropriate type before passing them to the procedure.

CALL now features implicit type conversion. I'll update the documentation accordingly.
